// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/Kaiya/kafka-chan/kafkapb/kafka-chan.proto

package kafkapb

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *QueryMsgByKeywordRequest) Validate() error {
	return nil
}
func (this *QueryMsgByKeywordReply) Validate() error {
	return nil
}
func (this *ProduceMsgToTopicRequest) Validate() error {
	return nil
}
func (this *ProduceMsgToTopicReply) Validate() error {
	return nil
}
func (this *MakeMemoryLRUCacheRequest) Validate() error {
	return nil
}
func (this *MakeMemoryLRUCacheReply) Validate() error {
	return nil
}
func (this *QueryMsgByOffsetReply) Validate() error {
	return nil
}
func (this *QueryMsgByOffsetRequest) Validate() error {
	return nil
}
